name: custom_world_news
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  json_annotation: ^4.8.1
  http: ^1.1.0

dev_dependencies: 
  flutter_lints: 3.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter: 
  uses-material-design: true

